# Importing All Necessary Modules
from datetime import date


def generateLoanId(id):
    # Creating A Date Object
    dt = str(date.today().strftime("%d%m"))

    # Converting Date into String to Generate User Id
    dt = dt.replace('-','')

    # print(id + dt)
    return str(id) + dt

if __name__ == '__main__':
    # pass the loan id generated by the User id generator.
    generateLoanId('20230225RA')